# Site settings
title: "Checksig: Custody for Crypto Assets"
name: CheckSig
email:
description: An implementation of the Opne Custody protocol.

#baseurl: http://checksig.io # the subpath of your site, e.g. /blog/
url: http://checksig.io
#logo: http://checksig.io/img/logo/cs-logo.png

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#disqus: checksig-1

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics: UA-126683188-2

include: [_pages]

# Build settings
markdown: kramdown

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
